#!/bin/sh
rm -r output
rm -r /tmp/serialconsole
meson --prefix=/tmp/serialconsole . output
meson compile -C output
meson install -C output
GSETTINGS_SCHEMA_DIR=/tmp/serialconsole/share/glib-2.0/schemas /tmp/serialconsole/bin/serialconsole
